[theme]
primaryColor = "#F63366" # couleur principale de l'interface
backgroundColor = "#4BB3FD" # couleur de fond de l'interface
secondaryBackgroundColor = "#F0F2F6" # couleur de fond secondaire
textColor = "#262730" # couleur du texte
font = "sans serif" # police d'écriture
